Update RpcServer.SmartContract.cs
neo-project/neo-modules pull request #400
Opened 2020-11-16 02:46 UTC by chenzhitong

close https://github.com/neo-project/neo-modules/issues/398

2020-11-16 11:19 UTC, shargon requested changes
I think that this properties can't be null or compute the `Hash` will fault.

2020-11-17 02:24 UTC, chenzhitong commented
> I think that this properties can't be null or compute the `Hash` will fault.

So we should make `signers` a normal parameter instead of an optional parameter?
``` c#
GetInvokeResult(byte[] script, Signers signers = null)
```

2020-11-17 07:38 UTC, superboyiii commented
> I think that this properties can't be null or compute the `Hash` will fault.

It could be null. If it's null, just do nothing in `ProcessInvokeWithWallet`.
https://github.com/neo-project/neo-modules/blob/2ae6a9722b7a6a031943f92866d53c89b18b3433/src/RpcServer/RpcServer.Wallet.cs#L168

2020-11-17 07:50 UTC, cloud8little commented
I think default  signers value should not be null when calling invokefunction and invokescript. It should be Array.Empty<Signer>().

https://github.com/neo-project/neo-modules/blob/2ae6a9722b7a6a031943f92866d53c89b18b3433/src/RpcServer/RpcServer.SmartContract.cs#L130

https://github.com/neo-project/neo-modules/blob/2ae6a9722b7a6a031943f92866d53c89b18b3433/src/RpcServer/RpcServer.SmartContract.cs#L116

2020-11-18 09:42 UTC, shargon commented
If `Hash` FAULT, It can FAULT here https://github.com/neo-project/neo/blob/2d0e6123a1f9e58c8069f0762d17c6e5eec2dde9/src/neo/Network/P2P/Payloads/Transaction.cs#L325

2020-11-19 09:25 UTC, superboyiii commented
> If `Hash` FAULT, It can FAULT here https://github.com/neo-project/neo/blob/2d0e6123a1f9e58c8069f0762d17c6e5eec2dde9/src/neo/Network/P2P/Payloads/Transaction.cs#L325

Hash will not be computed if `signer` is null. 
https://github.com/neo-project/neo-modules/blob/f13d7c305f02f77aa48cc579f678a96e4f319a25/src/RpcServer/RpcServer.Wallet.cs#L171

2020-11-19 09:43 UTC, shargon commented
Could you test it calling `InvokeFunction` to a method that return the hash of the current transaction?
https://github.com/neo-project/neo-modules/blob/8f03a7f78fa0de02385574b4aedc28b21c0d81c3/src/RpcServer/RpcServer.SmartContract.cs#L116

2020-11-20 03:36 UTC, superboyiii commented
> Could you test it calling `InvokeFunction` to a method that return the hash of the current transaction (without signer)?
> https://github.com/neo-project/neo-modules/blob/8f03a7f78fa0de02385574b4aedc28b21c0d81c3/src/RpcServer/RpcServer.SmartContract.cs#L116

Do you mean return hash in the internal of SC? If in this situation, it will truely return fault.

2020-11-20 03:37 UTC, Tommo-L commented
In some cases, we don't need to set `Signer`, like invoke `balanceOf` method.  And if the invoke return faults, the user need to check it.

2020-11-20 09:33 UTC, shargon commented on src/RpcServer/RpcServer.SmartContract.cs
>              Transaction tx = new Transaction
```suggestion
            Transaction tx = signers == null ? null : new Transaction
```

2020-11-20 10:01 UTC, shargon approved these changes

2020-11-20 10:03 UTC, merged