Nep17
neo-project/neo-modules pull request #412
Opened 2020-11-27 03:00 UTC by chenzhitong

2020-11-27 05:14 UTC, chenzhitong commented
TODO: Awaiting manifest data structure changes in the neo project, and fixe UT.

2020-11-28 12:23 UTC, vncoelho commented on src/RpcClient/Models/RpcNep5TokenInfo.cs
> +        public string Neme { get; set; }
```suggestion
        public string Name { get; set; }
```

2020-11-28 12:24 UTC, vncoelho commented on src/RpcClient/Nep17API.cs
> +                Neme = string.Empty,
```suggestion
                Name = string.Empty,
```

2020-12-02 08:21 UTC, superboyiii commented on README.md
> +### Rpc17Tracker
```suggestion
### RpcNep17Tracker
```

2020-12-02 09:00 UTC, shargon requested changes

2020-12-02 09:00 UTC, shargon commented on src/RpcClient/Models/RpcNep5Balances.cs
> +    public class RpcNep17Balances
File names with `Nep5`

2020-12-02 09:32 UTC, chenzhitong commented
`TestGetTokenInfo()` How do I fix this unit test? 
![image](https://user-images.githubusercontent.com/6295602/100854661-46bda480-34c4-11eb-97cd-6c62b01f061e.png)

2020-12-03 08:03 UTC, superboyiii commented
@shargon Works well on mine. Need your review again.

2020-12-04 06:09 UTC, superboyiii approved these changes

2020-12-04 10:40 UTC, shargon commented on src/RpcClient/RpcClient.cs
> +            var result = await RpcSendAsync(GetRpcName(), hash).ConfigureAwait(true);
This change it's not related to the PR, mistake?

2020-12-04 10:43 UTC, shargon commented on tests/Neo.Network.RPC.Tests/UT_WalletAPI.cs
> +                tranaction = await walletAPI.TransferAsync(NativeContract.GAS.Hash, 2, new[] { keyPair1.PublicKey }, new[] { keyPair1 }, UInt160.Zero, NativeContract.GAS.Factor * 100);
`transaction` this test was wrong designed because it has two possible paths. Pass, and Fail.

2020-12-07 08:34 UTC, shargon approved these changes

2020-12-07 08:57 UTC, merged