RocksDbStore usable from Blockchain Toolkit
neo-project/neo-modules pull request #498
Opened 2021-02-01 19:24 UTC by devhawk

2021-02-01 19:56 UTC, shargon approved these changes

2021-02-02 04:45 UTC, erikzhang requested changes

2021-02-02 04:45 UTC, erikzhang commented on src/RocksDBStore/Plugins/Storage/RocksDBStorageProvider.cs
> +    public class RocksDBStorageProvider : Plugin, IStorageProvider
The plugin name should not be changed. Otherwise it will cause problems in the cli.

2021-02-02 16:02 UTC, devhawk commented
FYI, after working on migrating neo express to work against neo master, I don't think I'll be able to use the standard RocksDb plugin in express after all. Express stores additional information such as app logs in alternative RocksDB columns. I don't think we want to add that developer-tool specific functionality to this plugin

2021-02-02 16:02 UTC, closed without merging