3.2.1
neo-project/neo-modules pull request #705
Opened 2022-04-18 08:30 UTC by superboyiii

2022-04-18 08:51 UTC, shargon approved these changes

2022-04-18 11:45 UTC, Liaojinghui approved these changes

2022-04-19 00:25 UTC, erikzhang requested changes

2022-04-19 00:25 UTC, erikzhang commented on src/OracleService/OracleService.csproj
> +    <PackageReference Include="NeoFS.API" Version="3.1.0-CI01329" />
NeoFS.API should be updated too.

2022-04-19 00:51 UTC, Liaojinghui submitted a review, later dismissed

2022-04-19 03:35 UTC, superboyiii commented on src/OracleService/OracleService.csproj
> +    <PackageReference Include="NeoFS.API" Version="3.1.0-CI01329" />
> NeoFS.API should be updated too.

Done.

2022-04-20 01:37 UTC, erikzhang submitted a review, later dismissed

2022-04-20 01:39 UTC, erikzhang commented
Wait for #698

2022-04-21 05:57 UTC, superboyiii commented
@erikzhang merge?

2022-04-21 06:27 UTC, erikzhang approved these changes

2022-04-21 06:30 UTC, merged