minimal recovery message from f to f+1
neo-project/neo-modules pull request #723
Opened 2022-06-04 10:59 UTC by Liaojinghui

#722

2022-06-04 11:00 UTC, Liaojinghui commented
@fyrchik

2022-06-04 11:54 UTC, fyrchik approved these changes

2022-06-04 13:09 UTC, shargon approved these changes

2022-06-05 11:27 UTC, vncoelho requested changes
I will double check.

2022-06-05 11:37 UTC, vncoelho commented
Give me 1 day just to double check and verify index and history.

2022-06-06 21:29 UTC, vncoelho approved these changes
In fact, this logic has passed through some modifications since dBFT 2.0 and this case reported has been missed.

2022-06-06 21:31 UTC, vncoelho commented on src/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
>                  // Limit recoveries to be sent from an upper limit of `f` nodes
```suggestion
                // Limit recoveries to be sent from an upper limit of `f + 1` nodes
```

2022-06-06 21:31 UTC, vncoelho approved these changes

2022-06-14 03:28 UTC, merged