DBFT: add dbft unit test
neo-project/neo-modules pull request #836
Opened 2023-10-11 13:09 UTC by Liaojinghui

add the unit test for dbft

2023-10-11 13:10 UTC, Liaojinghui commented
@igormcoelho Hey man, i tried my best to migrate this into N3, but there still a few accessible issues, i think you might delete them directly, so i will stop from here.

2023-10-11 21:14 UTC, cschuchardt88 requested changes

2023-10-11 21:14 UTC, cschuchardt88 commented on neo-modules.sln
> +EndProject
Should we use the `nuget` package instead? `github` actions is failing.

```suggestion

```

2023-11-08 08:21 UTC, shargon commented
@Liaojinghui please give me rights in your branch to change some small things

2023-11-08 08:37 UTC, shargon commented
@Liaojinghui ut fails

2023-11-08 08:38 UTC, Liaojinghui commented
my bad, this one should be marked as draft, @vncoelho want to build the unit test for dbft, haven't complete

2023-11-08 08:39 UTC, Liaojinghui commented
> @shargon my bad, this one should be marked as draft, @vncoelho want to build the unit test for dbft, haven't complete, @vncoelho will do the rest

2023-11-10 11:02 UTC, closed without merging