Expose counter for getnativecontracts
neo-project/neo-modules pull request #900
Opened 2024-05-02 20:43 UTC by roman-khimov

https://github.com/neo-project/neo/issues/2905 is incomplete without it.

2024-05-02 20:45 UTC, vncoelho reviewed
Looks good to me

2024-05-02 20:46 UTC, vncoelho reviewed
I will compile everything and test here today or tomorrow.

2024-05-02 21:52 UTC, cschuchardt88 requested changes
This breaks `RpcClient`, please update `RpcClient`.

2024-05-02 21:52 UTC, cschuchardt88 commented on src/RpcClient/Models/RpcNativeContract.cs
> -// Copyright (C) 2015-2024 The Neo Project.
Please put this back.

2024-05-03 07:45 UTC, shargon approved these changes
Simpler and better

2024-05-03 15:09 UTC, Jim8y approved these changes

2024-05-03 15:30 UTC, vncoelho approved these changes

2024-05-03 15:31 UTC, merged

2024-05-04 06:24 UTC, AnnaShaleva reviewed
I'm too slow, but it's a really nice way.